# Generated by Django 3.0.8 on 2020-07-19 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mini_wallet', '0002_deposit_wallet_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='customer_xid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
