# Generated by Django 3.0.8 on 2020-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_wallet', '0003_walletuser_customer_xid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
