# Generated by Django 3.0.8 on 2020-07-21 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mini_wallet', '0004_auto_20200719_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('deposited_or_withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('reference_id', models.UUIDField(unique=True)),
                ('transaction_status', models.CharField(choices=[('DT', 'Deposit'), ('WT', 'Withdrawal')], max_length=2)),
                ('deposited_or_withdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='withdrawn_by',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
